# -*- coding: utf-8 -*-
from miles.conf.appsettings import AppSettings


class WFSettings(AppSettings):

    WEBFACTION_TEST = True
    DEFAULT_WEBFACTION_DJANGO_VERSION = "1.1.1"

    DEFAULT_DJANGO_APPNAME = 'site'
    DEFAULT_DJANGO_DATABASE_ENGINE = 'postgresql'

    DJANGO_APP_MAIN_TYPE = 'djangotrunk_mw25_25'
    DJANGO_APP_MEDIA_TYPE = 'symlink_static_only'

settings = WFSettings()

## STANDRAD CONFIGURATIONS
#WEBFACTION_TEST = False
#WEBFACTION_HOSTNAME = "WebXXX"
#WEBFACTION_USERNAME = ""
#WEBFACTION_PASSWORD = ""
#WEBFACTION_URL = ""

#WEBFACTION_MAILBOX = ""
#WEBFACTION_EMAIL = ""

#WEBFACTION_APPNAME = ""

#WEBFACTION_DATABASE_NAME = ""
#WEBFACTION_DATABASE_PASSWORD = ""
#WEBFACTION_DATABASE_ENGINE = "postgresql"

#WEBFACTION_DJANGO_VERSION = "1.1.1"
#WEBFACTION_COMMAND_CHECKOUT = ""
